blank_issues_enabled: false
contact_links:
  - name: FPPS4 Troubleshooting/Support 
    url: https://discord.gg/up9qatpX7M
    about: For support and technical issues, please come to our Discord server.
